
all: build

build  : build-array build-matrix

build-array :
	make -C ./array/01-test
	make -C ./array/02-test
	make -C ./array/06-test
	make -C ./array/03-test
	make -C ./array/04-test
	make -C ./array/05-test

build-matrix:
	make -C ./matrix/01-test
	make -C ./matrix/02-test
	make -C ./matrix/03-test
	make -C ./matrix/04-test
	make -C ./matrix/05-test
	make -C ./matrix/06-test
	make -C ./matrix/07-test
	make -C ./matrix/08-test
	make -C ./matrix/09-test
	make -C ./matrix/10-test
	make -C ./matrix/11-test
clean  :
	make -C ./array/01-test clean
	make -C ./array/02-test clean
	make -C ./array/06-test clean
	make -C ./array/03-test clean
	make -C ./array/04-test clean
	make -C ./array/05-test clean
	make -C ./matrix/01-test clean
	make -C ./matrix/02-test clean
	make -C ./matrix/03-test clean
	make -C ./matrix/04-test clean
	make -C ./matrix/05-test clean
	make -C ./matrix/06-test clean
	make -C ./matrix/07-test clean
	make -C ./matrix/08-test clean
	make -C ./matrix/09-test clean
	make -C ./matrix/10-test clean
	make -C ./matrix/11-test clean
test   :
	make -C ./array/01-test test
	make -C ./array/02-test test
	make -C ./array/06-test test
	make -C ./array/03-test test
	make -C ./array/04-test test
	make -C ./array/05-test test
	make -C ./matrix/01-test test
	make -C ./matrix/02-test test
	make -C ./matrix/03-test test
	make -C ./matrix/04-test test
	make -C ./matrix/05-test test
	make -C ./matrix/06-test test
	make -C ./matrix/07-test test
	make -C ./matrix/08-test test
	make -C ./matrix/09-test test
	make -C ./matrix/10-test test
	make -C ./matrix/11-test test
